import { cn } from "@/lib/utils";
import "./globals.css";

import type { Metadata } from "next";
import { Inter, Work_Sans } from "next/font/google";

import { Header } from "@/widgets";

const inter = Inter({ subsets: ["latin"] });
const work_sans = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  authModal,
}: {
  children: React.ReactNode;
  authModal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, work_sans.className, "bg-hr-bg")}>
        <Header />
        {authModal}
        <div className="hr-h-body container">{children}</div>
      </body>
    </html>
  );
}
